#!/usr/bin/env bun

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { execSync } from "child_process"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const ccpiRoot = path.resolve(dir, "../../.tmp-ccpi")
const outDir = path.resolve(dir, "src/kilocode/ccpi")

const PLUGIN_CATEGORIES = [
  "devops",
  "testing",
  "security",
  "api-development",
  "productivity",
  "performance",
  "database",
  "ai-ml",
]

function escapeString(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$")
}

function rebrand(content: string): string {
  return content
    .replace(/Jeremy Longshore/g, "Legion CLI")
    .replace(/jeremy@intentsolutions\.io/g, "legion@legioncli.com")
    .replace(/Intent Solutions IO/g, "Legion CLI")
    .replace(/intentsolutions\.io/g, "legioncli.com")
    .replace(/jeremylongshore\/claude-code-plugins-plus-skills/g, "LegionCLI/plugins")
    .replace(/jeremylongshore\/claude-code-plugins/g, "LegionCLI/plugins")
    .replace(/Claude Code/g, "Legion CLI")
    .replace(/claude code/g, "legion cli")
    .replace(/claude-code/g, "legion")
    .replace(/Claude CLI/g, "Legion CLI")
    .replace(/Claude's/g, "Legion's")
    .replace(/CLAUDE\.md/g, "LEGION.md")
    .replace(/~\/\.claude\//g, "~/.legion/")
    .replace(/tonsofskills\.com/g, "plugins.legioncli.com")
    .replace(/@intentsolutionsio\//g, "@legioncli/")
    .replace(/compatible-with:\s*claude-code/g, "compatible-with: legion-cli")
}

interface SkillEntry {
  name: string
  description: string
  content: string
  category: string
}

function toVarName(prefix: string, name: string): string {
  return `${prefix}_${name.replace(/[^a-zA-Z0-9]/g, "_")}`
}

async function ensureRepo() {
  if (fs.existsSync(path.join(ccpiRoot, "plugins"))) {
    console.log("Using existing CCPI clone...")
    return
  }
  console.log("Cloning CCPI repository...")
  execSync(`git clone --depth 1 https://github.com/jeremylongshore/claude-code-plugins-plus-skills.git "${ccpiRoot}"`, {
    stdio: "inherit",
  })
}

async function collectSkills(): Promise<SkillEntry[]> {
  const entries: SkillEntry[] = []
  const pluginsDir = path.join(ccpiRoot, "plugins")

  for (const category of PLUGIN_CATEGORIES) {
    const catDir = path.join(pluginsDir, category)
    if (!fs.existsSync(catDir)) continue

    const plugins = await fs.promises.readdir(catDir, { withFileTypes: true })
    for (const plugin of plugins) {
      if (!plugin.isDirectory()) continue

      const skillFile = path.join(catDir, plugin.name, "skills", plugin.name, "SKILL.md")
      const altSkillFile = path.join(catDir, plugin.name, "SKILL.md")

      let skillPath = ""
      if (fs.existsSync(skillFile)) skillPath = skillFile
      else if (fs.existsSync(altSkillFile)) skillPath = altSkillFile
      else {
        const skillsDir = path.join(catDir, plugin.name, "skills")
        if (fs.existsSync(skillsDir)) {
          const skillDirs = await fs.promises.readdir(skillsDir, { withFileTypes: true })
          for (const sd of skillDirs) {
            if (sd.isDirectory()) {
              const md = path.join(skillsDir, sd.name, "SKILL.md")
              if (fs.existsSync(md)) {
                skillPath = md
                break
              }
            }
          }
        }
      }

      if (!skillPath) continue

      const raw = await fs.promises.readFile(skillPath, "utf-8")
      const fmMatch = raw.match(/^---\n([\s\S]*?)\n---/)
      let name = plugin.name
      let description = ""

      if (fmMatch) {
        const fm = fmMatch[1]
        const nameMatch = fm.match(/^name:\s*["']?(.+?)["']?\s*$/m)
        const descMatch = fm.match(/^description:\s*[|>]?\s*\n([\s\S]*?)(?=\n\w|\n---)/m)
        if (nameMatch) name = nameMatch[1].trim()
        if (descMatch) description = descMatch[1].trim().split("\n")[0]
      }

      entries.push({
        name,
        description: description || `Plugin: ${name}`,
        content: rebrand(raw),
        category,
      })
    }
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

async function generateSkills(entries: SkillEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-plugins.ts — DO NOT EDIT`,
    `// CCPI (Claude Code Plugins Plus Skills) bundled as built-in defaults`,
    `// Source: https://github.com/jeremylongshore/claude-code-plugins-plus-skills`,
    ``,
    `export interface CcpiSkill {`,
    `  name: string`,
    `  description: string`,
    `  content: string`,
    `  category: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("SKILL", entry.name)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const CCPI_SKILLS: CcpiSkill[] = [`)
  for (const entry of entries) {
    const varName = toVarName("SKILL", entry.name)
    lines.push(
      `  { name: ${JSON.stringify(entry.name)}, description: ${JSON.stringify(entry.description)}, content: ${varName}, category: ${JSON.stringify(entry.category)} },`,
    )
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function main() {
  console.log("Generating CCPI bundles...")

  await ensureRepo()
  await fs.promises.mkdir(outDir, { recursive: true })

  const skills = await collectSkills()

  console.log(`  Skills: ${skills.length} (from ${PLUGIN_CATEGORIES.length} categories)`)

  const skillsCode = await generateSkills(skills)

  await fs.promises.writeFile(path.join(outDir, "skills.ts"), skillsCode)

  console.log(`Generated files in ${outDir}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
