#!/usr/bin/env bun

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { execSync } from "child_process"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const ponytailRoot = path.resolve(dir, "../../.tmp-ponytail")
const outDir = path.resolve(dir, "src/kilocode/context")

function escapeString(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$")
}

function rebrand(content: string): string {
  return content
    .replace(/ponytail:/g, "context:")
    .replace(/Ponytail:/g, "Context:")
    .replace(/ponytail/g, "context")
    .replace(/Ponytail/g, "Context")
    .replace(/Claude Code/g, "Legion CLI")
    .replace(/claude code/g, "legion cli")
    .replace(/Claude CLI/g, "Legion CLI")
    .replace(/Claude's/g, "Legion's")
    .replace(/@dietrichgebert\/ponytail/g, "@legioncli/context")
    .replace(/DietrichGebert\/ponytail/g, "LegionCLI/context")
    .replace(/~\/\.config\/ponytail/g, "~/.config/context")
    .replace(/\.config\/ponytail/g, ".config/context")
    .replace(/PONYTAIL_DEFAULT_MODE/g, "CONTEXT_DEFAULT_MODE")
    .replace(/@ponytail/g, "@context")
    .replace(/\/ponytail/g, "/context")
}

interface SkillEntry {
  name: string
  description: string
  content: string
}

interface CommandEntry {
  name: string
  description: string
  content: string
}

function parseToml(text: string): { description: string; prompt: string } {
  const desc = text.match(/^description\s*=\s*"(.+)"$/m)?.[1] ?? ""
  const prompt = text.match(/^prompt\s*=\s*"([\s\S]*?)"$/m)?.[1] ?? ""
  return { description: desc, prompt }
}

function toVarName(prefix: string, name: string): string {
  return `${prefix}_${name.replace(/[^a-zA-Z0-9]/g, "_")}`
}

async function ensureRepo() {
  if (fs.existsSync(path.join(ponytailRoot, "skills"))) {
    console.log("Using existing ponytail clone...")
    return
  }
  console.log("Cloning ponytail repository...")
  execSync(`git clone --depth 1 https://github.com/DietrichGebert/ponytail.git "${ponytailRoot}"`, {
    stdio: "inherit",
  })
}

async function collectSkills(): Promise<SkillEntry[]> {
  const skillsDir = path.join(ponytailRoot, "skills")
  const entries: SkillEntry[] = []
  const dirs = await fs.promises.readdir(skillsDir, { withFileTypes: true })

  for (const d of dirs) {
    if (!d.isDirectory()) continue
    const skillFile = path.join(skillsDir, d.name, "SKILL.md")
    if (!fs.existsSync(skillFile)) continue

    const raw = await fs.promises.readFile(skillFile, "utf-8")
    const fmMatch = raw.match(/^---\n([\s\S]*?)\n---/)
    let name = d.name
    let description = ""

    if (fmMatch) {
      const fm = fmMatch[1]
      const nameMatch = fm.match(/^name:\s*(.+)$/m)
      const descMatch = fm.match(/^description:\s*(.+)$/m)
      if (nameMatch) name = nameMatch[1].trim()
      if (descMatch) description = descMatch[1].trim()
    }

    entries.push({ name: rebrand(name), description: rebrand(description), content: rebrand(raw) })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

async function collectCommands(): Promise<CommandEntry[]> {
  const commandsDir = path.join(ponytailRoot, "commands")
  const entries: CommandEntry[] = []
  const files = await fs.promises.readdir(commandsDir)

  for (const file of files) {
    if (!file.endsWith(".toml")) continue
    const raw = await fs.promises.readFile(path.join(commandsDir, file), "utf-8")
    const name = file.replace(/\.toml$/, "")
    const { description, prompt } = parseToml(raw)

    entries.push({ name: rebrand(name), description: rebrand(description), content: rebrand(prompt) })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

async function collectRules(): Promise<string> {
  const rulesFile = path.join(ponytailRoot, "AGENTS.md")
  const raw = await fs.promises.readFile(rulesFile, "utf-8")
  return rebrand(raw)
}

async function generateSkills(entries: SkillEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ponytail.ts — DO NOT EDIT`,
    `// Context (lazy senior dev mode) skills bundled as built-in defaults`,
    ``,
    `export interface ContextSkill {`,
    `  name: string`,
    `  description: string`,
    `  content: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("SKILL", entry.name)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const CONTEXT_SKILLS: ContextSkill[] = [`)
  for (const entry of entries) {
    const varName = toVarName("SKILL", entry.name)
    lines.push(
      `  { name: ${JSON.stringify(entry.name)}, description: ${JSON.stringify(entry.description)}, content: ${varName} },`,
    )
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function generateCommands(entries: CommandEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ponytail.ts — DO NOT EDIT`,
    `// Context (lazy senior dev mode) commands bundled as built-in defaults`,
    ``,
    `export interface ContextCommand {`,
    `  name: string`,
    `  description: string`,
    `  content: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("CMD", entry.name)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const CONTEXT_COMMANDS: ContextCommand[] = [`)
  for (const entry of entries) {
    const varName = toVarName("CMD", entry.name)
    lines.push(
      `  { name: ${JSON.stringify(entry.name)}, description: ${JSON.stringify(entry.description)}, content: ${varName} },`,
    )
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function generateRules(content: string): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ponytail.ts — DO NOT EDIT`,
    `// Context lazy senior dev ruleset`,
    ``,
    `export const CONTEXT_RULE = \`${escapeString(content)}\``,
    ``,
  ]

  return lines.join("\n")
}

async function main() {
  console.log("Generating Context bundles...")

  await ensureRepo()
  await fs.promises.mkdir(outDir, { recursive: true })

  const [skills, commands, rules] = await Promise.all([collectSkills(), collectCommands(), collectRules()])

  console.log(`  Skills: ${skills.length}`)
  console.log(`  Commands: ${commands.length}`)
  console.log(`  Rules: ${rules.length > 0 ? "1" : "0"}`)

  const [skillsCode, commandsCode, rulesCode] = await Promise.all([
    generateSkills(skills),
    generateCommands(commands),
    generateRules(rules),
  ])

  await Promise.all([
    fs.promises.writeFile(path.join(outDir, "skills.ts"), skillsCode),
    fs.promises.writeFile(path.join(outDir, "commands.ts"), commandsCode),
    fs.promises.writeFile(path.join(outDir, "rules.ts"), rulesCode),
  ])

  console.log(`Generated files in ${outDir}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
