#!/usr/bin/env bun

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const eccRoot = path.resolve(dir, "../../.tmp-ecc")
const outDir = path.resolve(dir, "src/kilocode/ecc")

function escapeString(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$")
}

interface SkillEntry {
  name: string
  description: string
  content: string
}

interface CommandEntry {
  name: string
  description: string
  content: string
}

interface AgentEntry {
  name: string
  description: string
  content: string
}

interface RuleEntry {
  language: string
  filename: string
  content: string
}

async function collectSkills(): Promise<SkillEntry[]> {
  const skillsDir = path.join(eccRoot, "skills")
  const entries: SkillEntry[] = []
  const dirs = await fs.promises.readdir(skillsDir, { withFileTypes: true })

  for (const dir of dirs) {
    if (!dir.isDirectory()) continue
    const skillFile = path.join(skillsDir, dir.name, "SKILL.md")
    if (!fs.existsSync(skillFile)) continue

    const raw = await fs.promises.readFile(skillFile, "utf-8")
    const fmMatch = raw.match(/^---\n([\s\S]*?)\n---/)
    let name = dir.name
    let description = ""

    if (fmMatch) {
      const fm = fmMatch[1]
      const nameMatch = fm.match(/^name:\s*(.+)$/m)
      const descMatch = fm.match(/^description:\s*(.+)$/m)
      if (nameMatch) name = nameMatch[1].trim()
      if (descMatch) description = descMatch[1].trim()
    }

    const content = raw
    entries.push({ name, description, content })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

async function collectCommands(): Promise<CommandEntry[]> {
  const commandsDir = path.join(eccRoot, "commands")
  const entries: CommandEntry[] = []
  const files = await fs.promises.readdir(commandsDir)

  for (const file of files) {
    if (!file.endsWith(".md")) continue
    const raw = await fs.promises.readFile(path.join(commandsDir, file), "utf-8")
    const name = file.replace(/\.md$/, "")
    let description = ""

    const fmMatch = raw.match(/^---\n([\s\S]*?)\n---/)
    if (fmMatch) {
      const fm = fmMatch[1]
      const descMatch = fm.match(/^description:\s*(.+)$/m)
      if (descMatch) description = descMatch[1].trim()
    }

    entries.push({ name, description, content: raw })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

async function collectAgents(): Promise<AgentEntry[]> {
  const agentsDir = path.join(eccRoot, "agents")
  const entries: AgentEntry[] = []
  const files = await fs.promises.readdir(agentsDir)

  for (const file of files) {
    if (!file.endsWith(".md")) continue
    const raw = await fs.promises.readFile(path.join(agentsDir, file), "utf-8")
    const name = file.replace(/\.md$/, "")
    let description = ""

    const fmMatch = raw.match(/^---\n([\s\S]*?)\n---/)
    if (fmMatch) {
      const fm = fmMatch[1]
      const descMatch = fm.match(/^description:\s*(.+)$/m)
      if (descMatch) description = descMatch[1].trim()
    }

    entries.push({ name, description, content: raw })
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

async function collectRules(): Promise<RuleEntry[]> {
  const rulesDir = path.join(eccRoot, "rules")
  const entries: RuleEntry[] = []
  const dirs = await fs.promises.readdir(rulesDir, { withFileTypes: true })

  for (const dir of dirs) {
    if (!dir.isDirectory()) continue
    const dirPath = path.join(rulesDir, dir.name)
    const files = await fs.promises.readdir(dirPath)
    for (const file of files) {
      if (!file.endsWith(".md")) continue
      const content = await fs.promises.readFile(path.join(dirPath, file), "utf-8")
      entries.push({ language: dir.name, filename: file, content })
    }
  }

  return entries.sort((a, b) => {
    const keyA = `${a.language}/${a.filename}`
    const keyB = `${b.language}/${b.filename}`
    return keyA.localeCompare(keyB)
  })
}

function toVarName(prefix: string, name: string): string {
  return `${prefix}_${name.replace(/[^a-zA-Z0-9]/g, "_")}`
}

async function generateSkills(entries: SkillEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ecc.ts — DO NOT EDIT`,
    `// ECC (Everything Claude Code) skills bundled as built-in defaults`,
    ``,
    `export interface EccSkill {`,
    `  name: string`,
    `  description: string`,
    `  content: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("SKILL", entry.name)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const ECC_SKILLS: EccSkill[] = [`)
  for (const entry of entries) {
    const varName = toVarName("SKILL", entry.name)
    lines.push(`  { name: ${JSON.stringify(entry.name)}, description: ${JSON.stringify(entry.description)}, content: ${varName} },`)
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function generateCommands(entries: CommandEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ecc.ts — DO NOT EDIT`,
    `// ECC (Everything Claude Code) commands bundled as built-in defaults`,
    ``,
    `export interface EccCommand {`,
    `  name: string`,
    `  description: string`,
    `  content: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("CMD", entry.name)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const ECC_COMMANDS: EccCommand[] = [`)
  for (const entry of entries) {
    const varName = toVarName("CMD", entry.name)
    lines.push(`  { name: ${JSON.stringify(entry.name)}, description: ${JSON.stringify(entry.description)}, content: ${varName} },`)
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function generateAgents(entries: AgentEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ecc.ts — DO NOT EDIT`,
    `// ECC (Everything Claude Code) agents bundled as built-in defaults`,
    ``,
    `export interface EccAgent {`,
    `  name: string`,
    `  description: string`,
    `  content: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("AGENT", entry.name)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const ECC_AGENTS: EccAgent[] = [`)
  for (const entry of entries) {
    const varName = toVarName("AGENT", entry.name)
    lines.push(`  { name: ${JSON.stringify(entry.name)}, description: ${JSON.stringify(entry.description)}, content: ${varName} },`)
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function generateRules(entries: RuleEntry[]): Promise<string> {
  const lines: string[] = [
    `// Auto-generated by script/generate-ecc.ts — DO NOT EDIT`,
    `// ECC (Everything Claude Code) language rules bundled as built-in instructions`,
    ``,
    `export interface EccRule {`,
    `  language: string`,
    `  filename: string`,
    `  content: string`,
    `}`,
    ``,
  ]

  for (const entry of entries) {
    const varName = toVarName("RULE", `${entry.language}_${entry.filename}`)
    lines.push(`const ${varName} = \`${escapeString(entry.content)}\``)
    lines.push("")
  }

  lines.push(`export const ECC_RULES: EccRule[] = [`)
  for (const entry of entries) {
    const varName = toVarName("RULE", `${entry.language}_${entry.filename}`)
    lines.push(`  { language: ${JSON.stringify(entry.language)}, filename: ${JSON.stringify(entry.filename)}, content: ${varName} },`)
  }
  lines.push(`]`)
  lines.push("")

  return lines.join("\n")
}

async function main() {
  console.log("Generating ECC bundles...")

  await fs.promises.mkdir(outDir, { recursive: true })

  const [skills, commands, agents, rules] = await Promise.all([
    collectSkills(),
    collectCommands(),
    collectAgents(),
    collectRules(),
  ])

  console.log(`  Skills: ${skills.length}`)
  console.log(`  Commands: ${commands.length}`)
  console.log(`  Agents: ${agents.length}`)
  console.log(`  Rules: ${rules.length}`)

  const [skillsCode, commandsCode, agentsCode, rulesCode] = await Promise.all([
    generateSkills(skills),
    generateCommands(commands),
    generateAgents(agents),
    generateRules(rules),
  ])

  await Promise.all([
    fs.promises.writeFile(path.join(outDir, "skills.ts"), skillsCode),
    fs.promises.writeFile(path.join(outDir, "commands.ts"), commandsCode),
    fs.promises.writeFile(path.join(outDir, "agents.ts"), agentsCode),
    fs.promises.writeFile(path.join(outDir, "rules.ts"), rulesCode),
  ])

  console.log(`Generated files in ${outDir}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
