// Auto-generated by script/generate-ponytail.ts — DO NOT EDIT
// Context (lazy senior dev mode) commands bundled as built-in defaults

export interface ContextCommand {
  name: string
  description: string
  content: string
}

const CMD_context = `Switch to context {{args}} mode. If no level specified, use full. Lazy senior dev mode, before any code: does it need to exist at all (YAGNI)? Does the standard library do it? A native platform feature? Can it be one line? Build the minimum that works. No unrequested abstractions, no avoidable dependencies, no boilerplate. Mark deliberate simplifications that cut a real corner with a known ceiling using a context: comment that names the ceiling and upgrade path.`

const CMD_context_audit = `Audit the entire repository for over-engineering only, not correctness. Scan the whole tree, not a diff. One line per finding, ranked biggest cut first: <tag> <what to cut>. <replacement>. [path]. Tags: delete (dead code/speculative feature), stdlib (reinvented standard library), native (dependency doing what the platform does), yagni (abstraction with one implementation), shrink (same logic, fewer lines). End with the net lines and dependencies removable. If nothing to cut: 'Lean already. Ship.'`

const CMD_context_debt = `Harvest every \`context:\` comment in this repository into a debt ledger so deferrals do not rot into 'later means never'. Grep the whole tree for comment markers (grep -rnE '(#|//) ?context:' ., skipping node_modules/.git/build output). One row per marker, grouped by file: <file>:<line> — <what was simplified>. ceiling: <the limit named in the comment>. upgrade: <the trigger to revisit>. Tag any marker that names no upgrade path or trigger as no-trigger, those rot silently. End with the count of markers and how many lack a trigger. If none: 'No context: debt. Clean ledger.' Report only, change nothing.`

const CMD_context_gain = `Show the context gain scoreboard. One shot, change nothing: do not switch mode, write flag files, or persist anything. Render the published benchmark medians (5 everyday tasks; models Haiku, Sonnet, Opus; source benchmarks/ and the README) as plain ASCII bars: Lines of code, no-skill 100% vs context 6-20% (down 80-94%); Cost, no-skill 100% vs context 23-53% (down 47-77%); Speed, context 3-6x faster. The bar length shows the measured range, the label carries the exact figure. These are benchmark medians, not this repo. NEVER print a per-repo savings number: the unbuilt version was never written, so there is no real baseline to subtract from in a live repo. For real per-repo figures, point to /context-debt (the counted shortcut ledger) and /context-audit (what is still cuttable). Report only.`

const CMD_context_help = `Show the context quick reference. One shot, change nothing: do not switch mode, write flag files, or persist anything. Levels: /context lite (build what's asked, name the lazier alternative in one line), /context (full, the default ladder: YAGNI then stdlib then native then one line then minimum), /context ultra (deletion before addition, challenges the requirement before building). Commands: /context-review (over-engineering review of the current changes), /context-audit (whole-repo over-engineering audit), /context-debt (harvest context: comments into a tracked ledger), /context-gain (measured-impact scoreboard from the benchmark), /context-help (this card). Deactivate with 'stop context', 'normal mode', or /context off; resume anytime with /context. Default mode is full; change it with the CONTEXT_DEFAULT_MODE environment variable (off|lite|full|ultra) or a config file at ~/.config/context/config.json (Windows: %APPDATA%\\\\context\\\\config.json) with {\\"defaultMode\\": \\"lite\\"}. Resolution order: env var, then config file, then full.`

const CMD_context_review = `Review the current code changes for over-engineering only, not correctness. One line per finding: L<line>: <tag> <what to cut>. <replacement>. Tags: delete (dead code/speculative feature), stdlib (reinvented standard library), native (dependency doing what the platform does), yagni (abstraction with one implementation), shrink (same logic, fewer lines). End with the net lines removable. If nothing to cut: 'Lean already. Ship.'`

export const CONTEXT_COMMANDS: ContextCommand[] = [
  { name: "context", description: "Switch context intensity level (lite/full/ultra/off)", content: CMD_context },
  { name: "context-audit", description: "Audit the whole repo for over-engineering, what can be deleted", content: CMD_context_audit },
  { name: "context-debt", description: "Harvest context: comments into a tracked debt ledger", content: CMD_context_debt },
  { name: "context-gain", description: "Show context's measured impact scoreboard (less code, cost, time)", content: CMD_context_gain },
  { name: "context-help", description: "Quick reference for context levels, skills, and commands", content: CMD_context_help },
  { name: "context-review", description: "Review changes for over-engineering, what can be deleted", content: CMD_context_review },
]
